### ISSUE TITLE
Lagging on fb_viewer.py (QT/GTK IDEs)

### ISSUE THREAD

**Issue by shimniok** [iabdalkader/openmv#27]
qt4-ide is lagging on fb_viewer.py with sleep(1) with reported 28fps. On my system using sleep(20) it runs 15fps without lag. Ibrahim reported unable to fix problems on his end. Awaiting more details.

We already know that there are race conditions between fb_dump() actions and omv internal framebuffer update. At certain QTimer() intervals within framebuffer.py the race conditions are apparent on my end; partial framebuffers are displayed, with a clear periodicity of how many lines are retrieved.

The qt4-ide uses a thread, versus the gtk idle task in the original IDE, and can run significantly more often and more efficiently which exacerbates the problem, I theorize. Waiting to be proven wrong.

**Comment by iabdalkader** [comment]
Seems to be working reasonable well now on "real machines" getting 20FPS @QVGA.
