### ISSUE TITLE
qt4-ide - unhandled KeyError while running fb_viewer.py

### ISSUE THREAD

**Issue by shimniok** [iabdalkader/openmv#28]
Never saw this before. While running fb_viewer.py with sleep(1), attempted to change value to sleep(20) and clicked run without stopping the existing script; caused a KeyError exception:

$ ./qt4-ide.py 
need to add openmv.find() before this can work...
[('/dev/ttyS0', 'ttyS0', 'PNP0501'), ('/dev/ttyACM0', 'ttyACM0', 'USB VID:PID=f055:9800 SNR=000000000011')]
JPEG decode error (not enough image data)
Exception KeyError: KeyError(140432758327040,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Object::disconnect: No such sig

**Comment by iabdalkader** [comment]
I'm closing all QT issues since we don't have a QT IDE anymore.
