### ISSUE TITLE
Openmv python IDE pyusb error

### ISSUE THREAD

**Issue by shraken** [iabdalkader/openmv#30]
Got my openmv in mail other day and running into some issues with IDE.  

I've tried on native Ubuntu 14.04, and my ubuntu 12.04 and Mint13 vmware/virtualbox setups.  The following test is on my vmware with ubuntu 14.04.  I get the error on all platforms I tested. 

I ran openmv-ide.py and successfully connected to the camera.  I can see the stm32f4 when I probe with lsusb as:
Bus 002 Device 004: ID f055:9800

I loaded the fb_viewer.py example file and clicked the cog link.  The output I get in my console is:
Traceback (most recent call last):
  File "openmv-ide.py", line 356, in execute_clicked
    openmv.exec_script(buf)
  File "/home/shraken/GitHub/openmv2/usr/openmv.py", line 130, in exec_script
    __dev.write(__OUT_EP, buf, __INTERFACE, __TIMEOUT)
TypeError: write() takes at most 4 arguments (5 given)

Googling... looks like some problem with pyusb breaking all old apps, see this thread:
https://bitbucket.org/benallard/galileo/issue/41/errors-in-kubuntu

I removed the __INTERFACE line and that gets rid of the warning on console but I still don't get an image.

**Comment by iabdalkader** [comment]
pyusb is not used in the IDE anymore (except in DFU upload)
