### ISSUE TITLE
Fails to link with gcc 4.9

### ISSUE THREAD

**Issue by festlv** [iabdalkader/openmv#44]
I was trying to compile latest openmv (9ddaca073190744c9ce0023da9c56a7f5beab9f8) with arm-none-eabi-gcc 4.9.2 but it fails with the following error:

    arm-none-eabi-cpp -P -E -DOPENMV1 omv/stm32f4xx.ld.S > /home/reinis/projects/ee/openmv/src/build/stm32f4xx.lds
    arm-none-eabi-gcc -mcpu=cortex-m4 -mabi=aapcs-linux -mthumb -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -nostdlib -Wl,--gc-sections -Wl,-T/home/reinis/projects/ee/openmv/src/build/stm32f4xx.lds /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/CommonTables/arm_common_tables.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/FastMathFunctions/arm_sqrt_q15.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/FastMathFunctions/arm_sqrt_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/FastMathFunctions/arm_sin_q15.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/FastMathFunctions/arm_sin_f32.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/FastMathFunctions/arm_cos_q15.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/FastMathFunctions/arm_cos_f32.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/FastMathFunctions/arm_sin_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/FastMathFunctions/arm_cos_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_mult_q15.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_mult_f32.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_scale_q15.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_scale_f32.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_mult_fast_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_mult_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_scale_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_inverse_f32.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_sub_q15.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_sub_f32.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_mult_fast_q15.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_sub_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_trans_q15.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_trans_f32.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_add_q15.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_init_f32.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_add_f32.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_trans_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_init_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_add_q31.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/dsp/MatrixFunctions/arm_mat_init_q15.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_rng.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_uart.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_tim.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_pcd_ex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_adc.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_pwr.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_spi.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_gpio.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_hcd.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_ll_fmc.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_flash_ex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_cortex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_tim_ex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_adc_ex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_dma.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_ll_sdmmc.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_rtc.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_rtc_ex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_i2c.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_ll_usb.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_dma_ex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_sd.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_rcc.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_flash.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_sdram.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_pwr_ex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_i2c_ex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_usart.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_dcmi.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_pcd.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal_rcc_ex.o /home/reinis/projects/ee/openmv/src/build/sthal/src/stm32f4xx_hal.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/patch.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/spi.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/inet_pton.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/evnt_handler.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/inet_ntop.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/wlan.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/security.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/netapp.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/hci.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/cc3000_common.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/patch_prog.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/socket.o /home/reinis/projects/ee/openmv/src/build/cc3k/src/nvmem.o /home/reinis/projects/ee/openmv/src/build/fatfs/src/ff.o /home/reinis/projects/ee/openmv/src/build/fatfs/src/option/ccsbcs.o /home/reinis/projects/ee/openmv/src/build/omv/main.o /home/reinis/projects/ee/openmv/src/build/omv/xalloc.o /home/reinis/projects/ee/openmv/src/build/omv/array.o /home/reinis/projects/ee/openmv/src/build/omv/usbdbg.o /home/reinis/projects/ee/openmv/src/build/omv/systick.o /home/reinis/projects/ee/openmv/src/build/omv/sccb.o /home/reinis/projects/ee/openmv/src/build/omv/ov9650.o /home/reinis/projects/ee/openmv/src/build/omv/ov2640.o /home/reinis/projects/ee/openmv/src/build/omv/sensor.o /home/reinis/projects/ee/openmv/src/build/omv/rng.o /home/reinis/projects/ee/openmv/src/build/omv/stm32f4xx_hal_msp.o /home/reinis/projects/ee/openmv/src/build/omv/soft_i2c.o /home/reinis/projects/ee/openmv/src/build/omv/mutex.o /home/reinis/projects/ee/openmv/src/build/omv/sdcard_spi.o /home/reinis/projects/ee/openmv/src/build/omv/img/blob.o /home/reinis/projects/ee/openmv/src/build/omv/img/fmath.o /home/reinis/projects/ee/openmv/src/build/omv/img/haar.o /home/reinis/projects/ee/openmv/src/build/omv/img/imlib.o /home/reinis/projects/ee/openmv/src/build/omv/img/integral.o /home/reinis/projects/ee/openmv/src/build/omv/img/kmeans.o /home/reinis/projects/ee/openmv/src/build/omv/img/lab.o /home/reinis/projects/ee/openmv/src/build/omv/img/rainbow_tab.o /home/reinis/projects/ee/openmv/src/build/omv/img/median.o /home/reinis/projects/ee/openmv/src/build/omv/img/point.o /home/reinis/projects/ee/openmv/src/build/omv/img/ppm.o /home/reinis/projects/ee/openmv/src/build/omv/img/rectangle.o /home/reinis/projects/ee/openmv/src/build/omv/img/fast.o /home/reinis/projects/ee/openmv/src/build/omv/img/freak.o /home/reinis/projects/ee/openmv/src/build/omv/img/template.o /home/reinis/projects/ee/openmv/src/build/omv/img/font.o /home/reinis/projects/ee/openmv/src/build/omv/img/jpeg.o /home/reinis/projects/ee/openmv/src/build/omv/img/lbp.o /home/reinis/projects/ee/openmv/src/build/omv/img/eye.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_led.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_sensor.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_image.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_time.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_clock.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_wlan.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_socket.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_select.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_gpio.o /home/reinis/projects/ee/openmv/src/build/omv/py/py_spi.o /home/reinis/projects/ee/openmv/src/build/omv/py/uart.o /home/reinis/projects/ee/openmv/src/build/omv/py/mlx90620.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/st/system_stm32f4xx.o /home/reinis/projects/ee/openmv/src/build/cmsis/src/st/startup_stm32f407xx.o /home/reinis/projects/ee/openmv/src/build/micropython/py/map.o /home/reinis/projects/ee/openmv/src/build/micropython/py/gc.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitinlinethumb.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objlist.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitcommon.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objfloat.o /home/reinis/projects/ee/openmv/src/build/micropython/py/modgc.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objmap.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objzip.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitnthumb.o /home/reinis/projects/ee/openmv/src/build/micropython/py/lexer.o /home/reinis/projects/ee/openmv/src/build/micropython/py/pfenv_printf.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objboundmeth.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objobject.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objstringio.o /home/reinis/projects/ee/openmv/src/build/micropython/py/stream.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objproperty.o /home/reinis/projects/ee/openmv/src/build/micropython/py/modmicropython.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objstrunicode.o /home/reinis/projects/ee/openmv/src/build/micropython/py/lexerunix.o /home/reinis/projects/ee/openmv/src/build/micropython/py/builtin.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objfun.o /home/reinis/projects/ee/openmv/src/build/micropython/py/modcmath.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objcomplex.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objclosure.o /home/reinis/projects/ee/openmv/src/build/micropython/py/builtinevex.o /home/reinis/projects/ee/openmv/src/build/micropython/py/parsenumbase.o /home/reinis/projects/ee/openmv/src/build/micropython/py/modio.o /home/reinis/projects/ee/openmv/src/build/micropython/py/obj.o /home/reinis/projects/ee/openmv/src/build/micropython/py/vstr.o /home/reinis/projects/ee/openmv/src/build/micropython/py/compile.o /home/reinis/projects/ee/openmv/src/build/micropython/py/nlrx86.o /home/reinis/projects/ee/openmv/src/build/micropython/py/modarray.o /home/reinis/projects/ee/openmv/src/build/micropython/py/argcheck.o /home/reinis/projects/ee/openmv/src/build/micropython/py/nlrx64.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objenumerate.o /home/reinis/projects/ee/openmv/src/build/micropython/py/vm.o /home/reinis/projects/ee/openmv/src/build/micropython/py/modmath.o /home/reinis/projects/ee/openmv/src/build/micropython/py/builtintables.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objtype.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objdict.o /home/reinis/projects/ee/openmv/src/build/micropython/py/modsys.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objtuple.o /home/reinis/projects/ee/openmv/src/build/micropython/py/asmarm.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objcell.o /home/reinis/projects/ee/openmv/src/build/micropython/py/runtime.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objset.o /home/reinis/projects/ee/openmv/src/build/micropython/py/smallint.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objfilter.o /home/reinis/projects/ee/openmv/src/build/micropython/py/unicode.o /home/reinis/projects/ee/openmv/src/build/micropython/py/parsenum.o /home/reinis/projects/ee/openmv/src/build/micropython/py/sequence.o /home/reinis/projects/ee/openmv/src/build/micropython/py/nativeglue.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitglue.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objmodule.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objint_mpz.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objslice.o /home/reinis/projects/ee/openmv/src/build/micropython/py/repl.o /home/reinis/projects/ee/openmv/src/build/micropython/py/lexerstr.o /home/reinis/projects/ee/openmv/src/build/micropython/py/builtinimport.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objint.o /home/reinis/projects/ee/openmv/src/build/micropython/py/formatfloat.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitcpy.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objgetitemiter.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitnx86.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objstr.o /home/reinis/projects/ee/openmv/src/build/micropython/py/bc.o /home/reinis/projects/ee/openmv/src/build/micropython/py/asmthumb.o /home/reinis/projects/ee/openmv/src/build/micropython/py/qstr.o /home/reinis/projects/ee/openmv/src/build/micropython/py/nlrthumb.o /home/reinis/projects/ee/openmv/src/build/micropython/py/opmethods.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objexcept.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitnx64.o /home/reinis/projects/ee/openmv/src/build/micropython/py/showbc.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objarray.o /home/reinis/projects/ee/openmv/src/build/micropython/py/stackctrl.o /home/reinis/projects/ee/openmv/src/build/micropython/py/modcollections.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitbc.o /home/reinis/projects/ee/openmv/src/build/micropython/py/mpz.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitpass1.o /home/reinis/projects/ee/openmv/src/build/micropython/py/asmx64.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objrange.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objbool.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objnone.o /home/reinis/projects/ee/openmv/src/build/micropython/py/binary.o /home/reinis/projects/ee/openmv/src/build/micropython/py/nlrsetjmp.o /home/reinis/projects/ee/openmv/src/build/micropython/py/parse.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objreversed.o /home/reinis/projects/ee/openmv/src/build/micropython/py/parsehelper.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objgenerator.o /home/reinis/projects/ee/openmv/src/build/micropython/py/malloc.o /home/reinis/projects/ee/openmv/src/build/micropython/py/emitnarm.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objint_longlong.o /home/reinis/projects/ee/openmv/src/build/micropython/py/asmx86.o /home/reinis/projects/ee/openmv/src/build/micropython/py/pfenv.o /home/reinis/projects/ee/openmv/src/build/micropython/py/scope.o /home/reinis/projects/ee/openmv/src/build/micropython/py/objnamedtuple.o /home/reinis/projects/ee/openmv/src/build/micropython/py/modstruct.o /home/reinis/projects/ee/openmv/src/build/micropython/stm32f4xx_it.o /home/reinis/projects/ee/openmv/src/build/micropython/string0.o /home/reinis/projects/ee/openmv/src/build/micropython/usbd_conf.o /home/reinis/projects/ee/openmv/src/build/micropython/usbd_desc_cdc_msc.o /home/reinis/projects/ee/openmv/src/build/micropython/usbd_cdc_interface.o /home/reinis/projects/ee/openmv/src/build/micropython/usbd_msc_storage.o /home/reinis/projects/ee/openmv/src/build/micropython/pendsv.o /home/reinis/projects/ee/openmv/src/build/micropython/bufhelper.o /home/reinis/projects/ee/openmv/src/build/micropython/usb.o /home/reinis/projects/ee/openmv/src/build/micropython/printf.o /home/reinis/projects/ee/openmv/src/build/micropython/gchelper.o /home/reinis/projects/ee/openmv/src/build/micropython/gccollect.o /home/reinis/projects/ee/openmv/src/build/micropython/pybstdio.o /home/reinis/projects/ee/openmv/src/build/micropython/readline.o /home/reinis/projects/ee/openmv/src/build/micropython/pyexec.o /home/reinis/projects/ee/openmv/src/build/micropython/help.o /home/reinis/projects/ee/openmv/src/build/micropython/input.o /home/reinis/projects/ee/openmv/src/build/micropython/import.o /home/reinis/projects/ee/openmv/src/build/micropython/lexerfatfs.o /home/reinis/projects/ee/openmv/src/build/micropython/flash.o /home/reinis/projects/ee/openmv/src/build/micropython/diskio.o /home/reinis/projects/ee/openmv/src/build/micropython/storage.o /home/reinis/projects/ee/openmv/src/build/micropython/file.o /home/reinis/projects/ee/openmv/src/build/micropython/rtc.o /home/reinis/projects/ee/openmv/src/build/micropython/pin.o /home/reinis/projects/ee/openmv/src/build/micropython/timer.o /home/reinis/projects/ee/openmv/src/build/micropython/servo.o /home/reinis/projects/ee/openmv/src/build/micropython/lib/libm/atanf.o /home/reinis/projects/ee/openmv/src/build/micropython/lib/libm/atan2f.o /home/reinis/projects/ee/openmv/src/build/micropython/lib/libm/math.o /home/reinis/projects/ee/openmv/src/build/micropython/lib/libm/mathsincos.o /home/reinis/projects/ee/openmv/src/build/micropython/lib/libm/fmodf.o /home/reinis/projects/ee/openmv/src/build/micropython/usbdev/core/src/usbd_core.o /home/reinis/projects/ee/openmv/src/build/micropython/usbdev/core/src/usbd_ctlreq.o /home/reinis/projects/ee/openmv/src/build/micropython/usbdev/core/src/usbd_ioreq.o /home/reinis/projects/ee/openmv/src/build/micropython/usbdev/class/cdc_msc_hid/src/usbd_cdc_msc_hid.o /home/reinis/projects/ee/openmv/src/build/micropython/usbdev/class/cdc_msc_hid/src/usbd_msc_bot.o /home/reinis/projects/ee/openmv/src/build/micropython/usbdev/class/cdc_msc_hid/src/usbd_msc_scsi.o /home/reinis/projects/ee/openmv/src/build/micropython/usbdev/class/cdc_msc_hid/src/usbd_msc_data.o  -o /home/reinis/projects/ee/openmv/src/build/openmv.elf
    /usr/lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: /home/reinis/projects/ee/openmv/src/build/openmv.elf section `.isr_vector' will not fit in region `FLASH_ISR'
    /usr/lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: region `FLASH_ISR' overflowed by 112 bytes
    collect2: error: ld returned 1 exit status
    Makefile:256: recipe for target '/home/reinis/projects/ee/openmv/src/build/openmv.elf' failed
    make: *** [/home/reinis/projects/ee/openmv/src/build/openmv.elf] Error 1

I'm not sure about the exact cause of this error, but I can report that the same code compiles cleanly on gcc 4.8. Feel free to close this issue- I'm reporting it so others can google the error message :>

**Comment by iabdalkader** [comment]
Fixed, you can compile with the 4.9 now, I think the old toolchain generated smaller object files that fit into the ISR section, anyway, I remove more object files from the ISR so it shouldn't matter anymore.
